from __future__ import annotations

from datetime import datetime, timezone
from html import escape

from gitmortem.git_analyzer import CommitFact

POSTMORTEM_TEMPLATE = """# Postmortem: {short_hash} - {severity}

> **{root_cause}**

## Incident Summary

| Field | Value |
|---|---|
| Commit | `{short_hash}` |
| Author | {author} |
| Timestamp | {timestamp} |
| Severity | {severity} |
| Estimated Impact | {impact} |
| Confidence | {confidence} |
| Time to Detect | {time_to_detect} |
| Deploy Pattern | {deploy_pattern} |

## Root Cause

**{root_cause}**

**Trigger:** {trigger}

**Contributing Factors**
{contributing_factors}

**Unknowns**
{unknowns}

## Blast Radius

**Files Changed:** {files_changed}

**Affected Systems:** {affected_systems}

{blast_radius_raw}

## Diff Highlights

```text
{diff_summary}
```

## Timeline

{timeline}

## Immediate Actions

{immediate_actions}

## Prevention Checklist

{prevention_items}

## Detection Improvements

{detection_improvements}

*Generated by gitmortem at {generated_at}*
"""

OFFLINE_TEMPLATE = """# Commit Report: {short_hash}

## Incident Summary

| Field | Value |
|---|---|
| Commit | `{short_hash}` |
| Author | {author} |
| Timestamp | {timestamp} |
| Files Changed | {file_count} |
| Insertions | {insertions} |
| Deletions | {deletions} |
| Mode | offline (`--no-llm`) |

## Commit Message

{message}

## Blast Radius

{blast_radius}

## Diff Highlights

```text
{diff_summary}
```

## Timeline

{timeline}

*Generated by gitmortem at {generated_at}*
"""

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    :root {{
      --bg: #0b1020;
      --panel: #121a31;
      --text: #e8edf9;
      --muted: #a9b5d1;
      --accent: #7dd3fc;
      --border: rgba(148, 163, 184, 0.2);
      --code: #0f172a;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: "Segoe UI", "SF Pro Display", sans-serif;
      background:
        radial-gradient(circle at top left, rgba(125, 211, 252, 0.18), transparent 25%),
        radial-gradient(circle at top right, rgba(96, 165, 250, 0.14), transparent 22%),
        linear-gradient(180deg, #08101f 0%, #0b1020 100%);
      color: var(--text);
      line-height: 1.6;
    }}
    main {{
      max-width: 960px;
      margin: 0 auto;
      padding: 48px 20px 64px;
    }}
    article {{
      background: rgba(18, 26, 49, 0.92);
      border: 1px solid var(--border);
      border-radius: 20px;
      padding: 32px;
      box-shadow: 0 30px 80px rgba(2, 6, 23, 0.45);
      backdrop-filter: blur(12px);
    }}
    h1, h2, h3 {{ color: white; }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }}
    th, td {{
      border: 1px solid var(--border);
      padding: 12px 14px;
      text-align: left;
      vertical-align: top;
      background: rgba(11, 16, 32, 0.35);
    }}
    th {{
      background: rgba(23, 33, 61, 0.95);
    }}
    code, pre {{
      font-family: "Cascadia Code", "SFMono-Regular", monospace;
    }}
    pre {{
      background: var(--code);
      border: 1px solid var(--border);
      padding: 16px;
      border-radius: 14px;
      overflow: auto;
    }}
    blockquote {{
      margin: 0 0 24px;
      padding: 16px 20px;
      border-left: 4px solid var(--accent);
      background: rgba(23, 33, 61, 0.85);
      border-radius: 12px;
    }}
  </style>
</head>
<body>
  <main>
    <article>
      {body}
    </article>
  </main>
</body>
</html>
"""


def render_markdown(
    commit_fact: CommitFact,
    diff_summary: str,
    root_cause: dict,
    timeline: dict,
    checklist: dict,
    blast_radius_text: str,
) -> str:
    contributing = _bullet_lines(root_cause.get("contributing_factors") or ["None identified."])
    unknowns = _bullet_lines(root_cause.get("unknowns") or ["None."])
    affected_systems = ", ".join(root_cause.get("affected_systems") or ["unknown"])

    timeline_table = _render_timeline_table(timeline.get("timeline", []))
    immediate_actions = (
        "\n".join(
            f"- **[{item['priority']}]** {item['action']} *(owner: {item['owner']})*"
            for item in checklist.get("immediate_actions", [])
        )
        or "- None generated."
    )
    prevention_items = (
        "\n".join(
            f"- `{item['type'].upper()}` {item['item']}"
            for item in checklist.get("prevention_items", [])
        )
        or "- None generated."
    )
    detection_improvements = _bullet_lines(
        checklist.get("detection_improvements") or ["No detection improvements suggested."]
    )

    return POSTMORTEM_TEMPLATE.format(
        short_hash=commit_fact.short_hash,
        severity=checklist.get("severity", "SEV3"),
        root_cause=root_cause.get("root_cause", "Unable to determine root cause."),
        author=commit_fact.author,
        timestamp=commit_fact.timestamp,
        impact=checklist.get("estimated_impact", "unknown"),
        confidence=root_cause.get("confidence", "unknown"),
        time_to_detect=timeline.get("time_to_detect", "unknown"),
        deploy_pattern=timeline.get("deploy_pattern", "unknown"),
        trigger=root_cause.get("trigger", "unknown"),
        contributing_factors=contributing,
        unknowns=unknowns,
        files_changed=", ".join(f"`{name}`" for name in commit_fact.files_changed[:8]) or "none",
        affected_systems=affected_systems,
        blast_radius_raw=blast_radius_text,
        diff_summary=diff_summary,
        timeline=timeline_table,
        immediate_actions=immediate_actions,
        prevention_items=prevention_items,
        detection_improvements=detection_improvements,
        generated_at=_generated_at(),
    )


def render_offline_markdown(
    commit_fact: CommitFact,
    diff_summary: str,
    blast_radius_text: str,
    timeline: dict,
) -> str:
    return OFFLINE_TEMPLATE.format(
        short_hash=commit_fact.short_hash,
        author=commit_fact.author,
        timestamp=commit_fact.timestamp,
        file_count=len(commit_fact.files_changed),
        insertions=commit_fact.insertions,
        deletions=commit_fact.deletions,
        message=commit_fact.message,
        blast_radius=blast_radius_text,
        diff_summary=diff_summary,
        timeline=_render_timeline_table(timeline.get("timeline", [])),
        generated_at=_generated_at(),
    )


def render_html(markdown_report: str, title: str) -> str:
    try:
        import markdown
    except ImportError as exc:
        raise RuntimeError("HTML export requires the 'markdown' package.") from exc

    body = markdown.markdown(markdown_report, extensions=["tables", "fenced_code"])
    return HTML_TEMPLATE.format(title=escape(title), body=body)


def _render_timeline_table(events: list[dict]) -> str:
    lines = ["| Time | Event | Hash |", "|---|---|---|"]
    for event in events:
        lines.append(
            f"| {event.get('time', 'unknown')} | {event.get('event', 'unknown')} | "
            f"`{event.get('hash', '')}` |"
        )
    return "\n".join(lines)


def _bullet_lines(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def _generated_at() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
